exports.manager=function(c){
	c.RenderRecordView({
		label_en:"role manager",
		label_cn:"角色管理",
		data_action:c.AuthUrl("role.manager_data")});
}
exports.manager_data=function(c){
	c.RenderJson( {data:[{name: "Moroni", age: 50,t1:12,t2:2,t3:33,t4:33},
                     {name: "Tiancum", age: 43},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Nephi", age: 29},
                     {name: "Enos", age: 34}]});
}
