exports.manager=function(c){
	c.RenderRecordView({
		data_action:c.AuthUrl("role.manager_data")});
}
exports.manager_data=function(c){
	c.RenderJson( {
		columns:[
			{fieldName:"name",dataType:"string"},
			{fieldName:"age",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"},
			{fieldName:"age1",dataType:"int64"}
		],
		data:[{name: "责任人观后感阿德的的的", age: 50,T1:1,T2:2,T3:3,T4:3,T6:3,T7:3,T8:3,T9:33,T1212121212121212121:333},
                     {name: "Tiancum", age: 43},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Nephi", age: 29},
                     {name: "Enos", age: 34}]});
}
