exports.manager=function(c){
	c.RenderRecordView({
		data_action:c.AuthUrl("role.manager_data")});
}
exports.manager_data=function(c){
	c.RenderJson( {
		columns:[
			{fieldName:"name",displayName:{en:"name",cn:"名称"},dataType:"string"},
			{fieldName:"age",displayName:{en:"age",cn:"年龄"},dataType:"int64"},
			{fieldName:"age1",displayName:{en:"age1",cn:"年龄1"},dataType:"int64"},
			{fieldName:"age2",displayName:{en:"age2",cn:"年龄2"},dataType:"int64"},
			{fieldName:"age3",displayName:{en:"age3",cn:"年龄3"},dataType:"int64"},
			{fieldName:"age4",displayName:{en:"age4",cn:"年龄4"},dataType:"int64"},
			{fieldName:"age5",displayName:{en:"age5",cn:"年龄5"},dataType:"int64"},
			{fieldName:"age6",displayName:{en:"age6",cn:"年龄6"},dataType:"int64"},
			{fieldName:"age7",displayName:{en:"age7",cn:"年龄7"},dataType:"int64"},
			{fieldName:"age8",displayName:{en:"age8",cn:"年龄8"},dataType:"int64"},
			{fieldName:"age9",displayName:{en:"age9",cn:"年龄9"},dataType:"int64"},
			{fieldName:"age10",displayName:{en:"age10",cn:"年龄10"},dataType:"int64"},
			{fieldName:"age11",displayName:{en:"age11",cn:"年龄11"},dataType:"int64"},
			{fieldName:"age12",displayName:{en:"age12",cn:"年龄12"},dataType:"int64"},
			{fieldName:"age13",displayName:{en:"age13",cn:"年龄13"},dataType:"int64"},
			{fieldName:"age14",displayName:{en:"age14",cn:"年龄14"},dataType:"int64"},
			{fieldName:"age15",displayName:{en:"age15",cn:"年龄15"},dataType:"int64"},
			{fieldName:"age16",displayName:{en:"age16",cn:"年龄16"},dataType:"int64"},
			{fieldName:"age17",displayName:{en:"age17",cn:"年龄17"},dataType:"int64"},
			{fieldName:"age18",displayName:{en:"age18",cn:"年龄18"},dataType:"int64"},
			{fieldName:"age19",displayName:{en:"age19",cn:"年龄19"},dataType:"int64"},
			{fieldName:"age20",displayName:{en:"age20",cn:"年龄20"},dataType:"int64"}
		],
		data:[{name: "责任人观后感阿德的的的", age: 50,T1:1,T2:2,T3:3,T4:3,T6:3,T7:3,T8:3,T9:33,T1212121212121212121:333},
                     {name: "Tiancum", age: 43},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Jacob", age: 27},
                     {name: "Nephi", age: 29},
                     {name: "Enos", age: 34}]});
}
